### ISSUE TITLE
Ensure Table of Contents is sorted alphabetically

### ISSUE THREAD

**Issue by raymelon** [raymelon/scripting-recipes#10]
An ideal solution is to implement an automated workflow that will update [README.md > Table of Contents](scrpting-recipes/README.md#table-of-contents).

Workflow flow:

1. Start workflow after a commit on main branch
2. Parse README.md file
3. For each language section on Table of Contents:
3.1. Extract script filenames
3.2. Sort the script filenames alphabetically 
3.3. Rewrite the language section
4. Commit to main branch and push

Anyone interested to implement this, let me know. Will include this in Hacktoberfest 2023.
I'm also open to discussions, feel free to reply with your suggestions.

**Comment by Chibuike-edmund** [comment]
@raymelon 

Kindly Check in

I kinda tweaked with this somehow

**Comment by raymelon** [comment]
Checking it out @Chibuike-edmund ! Appreciate the Pull Request and implementing it!

**Comment by raymelon** [comment]
Adding [Pull Request #11](https://github.com/raymelon/scripting-recipes/pull/11)

Contributed by @Chibuike-edmund

**Comment by raymelon** [comment]
Tried the test merge, see the Actions log:

https://github.com/raymelon/scripting-recipes/actions/runs/6495866893

Encountered this.

Resolved by using updated versions of actions (v3) as suggested here [Node.js 12 to 16](https://github.com/actions/checkout/issues/1047#issuecomment-1355170319)

See resolution at [Commit c0ca9](https://github.com/raymelon/scripting-recipes/commit/c0ca9023f1d4675dd90b80770f73a0cd15ba696c)

![image](https://github.com/raymelon/scripting-recipes/assets/23053494/8d3e39f4-fc06-4e4f-8f0f-02c4eba6182e)

**Comment by raymelon** [comment]
Hi @Chibuike-edmund, kindly take a look at the [Job Log](https://github.com/raymelon/scripting-recipes/actions/runs/6496005897/job/17642056308)

![image](https://github.com/raymelon/scripting-recipes/assets/23053494/2d576e0b-958b-4623-84d0-6fc7acacd91f)

I tried adding an entry on the top of [Bash](https://github.com/raymelon/scripting-recipes#bash-) section, but the GitHub Action did not update the README file.

**Comment by georgettica** [comment]
is your issue that the other types are not sorted? I think this is the case as the code only looks at python segments.

if you want the others to be changed a simple refactor to the code can be done

**Comment by raymelon** [comment]
@georgettica Hi, thank you for your comment. You're right, the script only looks at python segments.

With that, I also did the same thing for the Python segment. The Action ran, but the README file is not updated still.

Is the step `4. Commit to main branch and push even possible?` What do you think?

> Workflow flow:
> 
> 1. Start workflow after a commit on main branch
> 2. Parse README.md file
> For each language section on Table of Contents:
> 3.1. Extract script filenames
> 3.2. Sort the script filenames alphabetically
> 3.3. Rewrite the language section
> 4. Commit to main branch and push

**Comment by georgettica** [comment]
It's more on each PR it will add a commit and push there than on the main branch.

And it's possible

**Comment by raymelon** [comment]
Closing the issue. I modified update_readme to work as I intended. Appreciate everyone who contributed!
